# Generated by Django 5.2.1 on 2025-05-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_teaseritem_seller_name_teaseritem_store_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaseritem',
            old_name='expires_at',
            new_name='Available',
        ),
    ]
